
<p align="justify"><a href="http://www.ekrishok.com"><strong>e-Krishok: Agricultural Information & Advisory and Market Linkage Services for Farmers </strong> </a></p>
<p align="justify">BIID's agricultural service is branded as e-Krishok, an initiative which is aimed at farmers with the desired goal of providing services from which farmers will benefit both in terms of their farming activities and opening up opportunities in new avenues which will ultimately translate into increased income for farmers. Farmers with any problem or query or issue which is related to agriculture can go to nearby ICT enabled Information Center / Telecentres and receive the information that they are seeking. The information usually provided to them in a timely and quick manner, so that the farmers can get on with their activities. With such timely and appropriate information, farmers will be able to maximize their economic gain; enabling them to achieve income growth through agricultural activities. e-Krishok is now in a process of transforming into a transactional service. BIID in collaboration with Grameen Phone (GP) introduced SMS/call back service via Short Code.</p>
<p align="justify"><strong>ICT Strategy for AECB Project jointly with MEAS</strong> </a></p>
<p align="justify">The Modernizing Extension and Advisory Services (MEAS) project has been launched with the support of USAID and is focused on the integration of Information and Communication Technologies (ICTs) into agricultural extension services. This is a complementary extension support program of another project designed by the USAID, the Agricultural Extension Capacity Building (AECB), which is intended to strengthen extension and advisory services in Bangladesh, specifically in the Feed the Future target regions. MEAS proposes to provide support to the AECB project in achieving success under what is designated as Intervention 2 of AECB, namely the expansion of the use of ICTs to support the provision of extension services. MEAS will provide technical support for the following four tasks of AECB:<br />
&ndash;	Development of a Strategy for Extension of the use of Information and Communication Technologies ICTs) in Extension Services.<br />
&ndash;	Training of Farmers and Extension Agents in the use of ICTs.<br />
&ndash;	Trainings held by Extension Agents using ICTs.<br />
&ndash;	Multimedia Extension Products created using ICTs. <br />
The major task of the MEAS support to AECB is to develop the ICT strategy and build capacity among the AECB partners and stakeholders. A timeline for the first year includes six months of support in development of a strategy and the remaining six months in implementation of the project. This project will be implemented under the joint leadership of the University of Illinois at Urbana Champaign (ILLINOIS) and the University of California at Davis (UCD) in conjunction with BIID and Access Agriculture as partners.                                                                                                                                                                                                                 
</p>
<p align="justify"><strong>Intel&reg; Easy Steps: A Digital Literacy Program</strong></p>
<p align="justify">Intel Corporation signed a memorandum of understanding (MoU) with BIID for deployment of the Intel&reg; Easy Steps Program in Bangladesh. The Intel&reg; Easy Steps program offers adult learners the opportunity for enhanced social and economic self sufficiency through digital literacy. The Intel Easy Steps materials use adult learning techniques to teach practical and applicable skills to people with minimum computer knowledge. The Intel&reg; Easy Steps program is being carried out by Intel in Asia to address the digital literacy needs of government employees, as well as adults in rural communities, women, unemployed youth, and other underserved populations. A government needs ICT-literate labor for a competitive workforce which would bring about a competitive economy. On the other hand participants have an opportunity to improve skills thus enhancing their employment prospects. The program includes instructions on running Internet searches, using email, using word processors for creating resumes and other documents, creating spreadsheets, and using multimedia tools to create brochures and posters to promote small businesses. Thus the trainees can develop literacy skills and immediately start applying them into their personal or professional lives. BIID will facilitate value added services for the trainees to end up with a job opportunity or get self employed with support from relevant stakeholders.</p>
<p align="justify"><strong>e-Services through Short Code 16250</strong></p>
<p align="justify">BIID has taken the initiative to launch a new service to offer e-Information through Short Code 16250, as a helpline service dedicated to providing information covering a wide range of areas ensuring people&rsquo;s right to information at the right time. Access to accurate information is crucial but is often unavailable to many due to various reasons; this essentially handicaps citizens of the country by denying them the right to information at any given time. To alleviate such constraints BIID identified following sectors to cover and offer detailed information on services: <br />
  &ndash;	Agriculture<br />
  &ndash;	Education<br />
  &ndash;	Health Care<br />
  &ndash;	Micro, Small and Medium Enterprises (MSME)<br />
  &ndash;	Tourism<br />
  &ndash;	Jobs<br />
  &ndash;	Complain <br />
  &ndash;	Emergency <br />
  The above mentioned areas of service have been selected in order to cater to a wide cross-section of people. These options provide information which cover basic grounds for majority of callers. The project will be piloted with these initial categories but there is scope to expand based on public requirements.</p>
<p align="justify"><a href="http://www.eclinicbd.com"><strong>e-Clinic: Bringing Quality Health Service to Rural Areas</strong></a></p>
<p align="justify">BIID initiated e-Clinic project to bring quality health service to rural areas where Telemedicine has been identified as one of the most potential tool to bridge the gap. Considering the present health care facilities in Bangladesh, BIID has taken the initiative to start an interactive healthcare facility by utilizing modern technology blended with ICT tools. The e-Clinic project will cover the awareness building initiatives on health care among the rural communities and will use video consultations and other ICT based tools to offer basic primary health care services in rural settings. The rural underprivileged communities, mainly the women and children groups will be served with quality health care facilities of which they are deprived most. In the pilot phase, there will be a Central Management Unit (CMU) located in Dhaka equipped with 'state of art' technologies and qualified health professionals, and 10 Service Delivery Points at different parts of the country with basic ICT infrastructure. The rural communities will be served in a sustainable manner by offering e-health facilities with the support of existing health service providers including the health professionals working in the rural areas. Continued Medical Education (CME) will also be introduced through the network of e-Clinic.</p>
<p align="justify"><a href="http://www.gpcic.org"><strong>GP CIC: Developing Services for GP CICs  </strong> </a></p>
<p align="justify">BIID is engaged in supporting Community Information Centers (CIC) of GP to replicate and expand the existing services of CIC's across the country. BIID is also engaged in the process to build the capacity of the CIC entrepreneurs to provide better services and facilities to the customers thereby adding value to the user experience of the customers.</p>
<p align="justify"><a href="http://www.travelline.com.bd"><strong>Travel Line: Providing Information and Solutions to travelers </strong> </a></p>
<p align="justify">Travel Line is a service which will provide tourism related information and online booking facility to the tourists. Whenever a potential tourist wants information about a particular place in Bangladesh-such as what hotels are available, what the transport options are, what are the costs, how to get there, etc., that person can get in touch with Travel Line for the information, and they will be able to get the information conveniently. BIID in collaboration with Banglalink; second largest Mobile Network Operator (MNO) in Bangladesh, is offering voice based/ call centre service to provide tourism related information through short code 707. The service is also available in web based platform.</p>
<p align="justify"><a href="http://www.extension.org.bd"><strong>eXtension.org.bd: An online platform in Agricultural extension </strong></a></p>
<p align="justify">BIID and Sher-E-Bangla Agricultural University (SAU) jointly launched the www.extension.org.bd portal to establish an ICT based knowledge sharing platform for various stakeholders of agricultural extension. This online platform will foster usage of ICT in agricultural extension to faster growth in the agriculture sector through knowledge sharing, consequently enhancing the efficiency of knowledge &amp; skill of expertise on continuous basis of relevant stakeholders including researchers, extension officers, academicians, policy makers, private sectors, media, development agencies, NGOs etc. Instrumentally, it will coordinate among these stakeholders and link the research to field, provide relevant and updated extension related information to the people on a more regular basis. BIID foresee this platform as a knowledge hub for policy makers, academician and extension workers.</p>
<p align="justify"><strong>Batighar: An inclusive business model for telecenters </strong> </p>
<p align="justify">After successful piloting phase, BIID has introduced the Batighar (Light House) information centre based on inclusive business model for scaling up in all over the country. Batighar, the name derived from the English word &quot;lighthouse&quot;, is meant to show people correct direction. Recently, BIID rolled out 10 Batighar centres all over the country. This particular business model can be distinctively characterized as a structured commercial model for for-profit telecenter ventures, which, are undertaken by entrepreneurs, businesses and organizations. It can also be termed as &quot;entrepreneurship model&quot;.</p>
<p align="justify"><a href="http://www.biidtanzania.com"><strong>BIID Tanzania Launched</strong></a></p>
<p align="justify">BIID extended its work in Africa region and launched BIID Tanzania (BT) as the hub for East African Communities (EAC) countries. In 2010-11, BIID successfully conducted a Joint Impact Assessment, Services Need Analysis and Designing Business Model Towards Developing A Sustainable Network of Telecentres in The United Republic of Tanzania jointly with Tanzania Communication Regulatory Authority (TCRA) and Tanzania Telecentre Network (TTN) to assess the impact of Telecentres and develop a business model to serve the rural underprivileged communities towards improvement of livelihood by using ICT tools. BIID Tanzania will offer research in broader ICT4D, development of ICT enabled products and services to support private, non-government and government initiatives targeted at rural communities in particular and citizens in general.</p>
<p align="justify"><a href="http://www.gpcic.org"><strong>SME: Online Advisory Service. </strong> </a></p>
<p align="justify">BIID launched an integrated initiative in Bangladesh to facilitate the rapid growth of the Micro, Small and Medium Enterprises (MSMEs) with the help of ICT in addressing their problem and providing suitable solution to them. Developing the ICT-based platform to offer information and services for the rural enterprises will be an effective strategy to enhance the competitiveness of the rural MSMEs who have, among others, need for information on new markets, better business practices, and business promotion ideas where technology can become the catalyst to help the enterprises access the same. Empowering through new market linkages and building capacity of the MSMEs will ultimately contribute to the growth and competitiveness in this sector. MSME portal will also be focusing on the access to finance issue as well as training facilities for the MSMEs'.<a href="http://www.complain.com.bd">
</a></p>
<p align="justify"><a href="http://www.complain.com.bd"><strong>e-Complain: Providing a Platform to Promote Rights Based Activities </strong></a></p>
<p align="justify">BIID has introduced an ICT enabled web based consumer &amp; citizen rights advocacy portal and online complaint handling mechanism, www.complain.com.bd. This unique web portal will allow the consumers/citizens a distinct platform and opportunity to be vocal about their rights, concerns and issues. Simultaneously the purpose is also to raise awareness, educate and empower the consumer on consumer rights and the legal protection afforded to them. </p>
<p align="justify"><strong>District Resource Center: Developing Local Support Services for Telecenters </strong> </p>
<p align="justify">BIID is the designated District Resource Center (DRC) for Dhaka district. A DRC is a district coordinating body located in a district headquarter, which is to be designed as a hub for promoting activities surrounding building information and knowledge system for all citizens. DRCs are conceptualized as independent institutions to be affiliated with the BTN. DRC is the official institution to promote and support entrepreneurs and institutions in establishment and operation of telecenters and other type of public access to information and knowledge through ICTs. To ensure sustainability and quality of services, DRC's will charge nominal fees for its diversified services.</p>
<p align="justify">&nbsp;</p>
