
<a href="http://www.ekrishok.com"><p><strong>e-Krishok: Agricultural Services for Rural Farmers </strong> </p></a>
<p>BIID's agricultural service for rural farmers, e-Krishok, is a campaign which is aimed at farmers with the desired goal of providing services from which farmers will benefit both in terms of their farming activities and opening up opportunities in new avenues which will ultimately translate into increased income for farmers. Farmers with any problem or query or issue which is related to agriculture can go to their local GP Community Information Center and receive the information that they are seeking. The information will be provided to them in a timely and quick manner, so that the farmers can get on with their activities. With such timely and appropriate information, farmers will be able to maximize their economic gain; enabling them to achieve income growth through agricultural activities.</p>
<a href="http://www.biidtanzania.com"><p><strong>BIID Tanzania Launched</strong></p></a>
<p>BIID extended its work in Africa region and launched BIID Tanzania (BT) as the hub for East African Communities (EAC) countries. Meantime, BIID successfully conducted a Joint Impact Assessment, Services Need Analysis and Designing Business Model Towards Developing A Sustainable Network of Telecentres in The United Republic of Tanzania jointly with Tanzania Communication Regulatory Authority (TCRA) and Tanzania Telecentre Network (TTN) to assess the impact of Telecentres and develop a business model to serve the rural underprivileged communities towards improvement of livelihood by using ICT tools.<a href="http://www.biid.org.bd/index.php?detail=tanzania">>>more</a></p>
<a href="http://www.gpcic.org"><p><strong>GP CIC: Supporting and Scaling up of GP CICs </strong> </p></a>
<p>BIID is engaged in supporting GP with their GP Community Information Center; to replicate and expand the existing number of CIC's across the country from 500 to over 1000. BIID is also engaged in the process to build the capacity of the CIC entrepreneurs to provide better services and facilities to the customers thereby adding value to the user experience of the customers.</p>
<a href="http://www.travelline.com.bd"><p><strong>Travel Line: Providing Information and Solutions to travelers </strong> </p></a>
<p>Travel Line is a service which will provide tourism related information to potential tourists.  Whenever a potential tourist wants information about a particular place in Bangladesh-such as what hotels are available, what the transport options are, what are the costs, how to get there, etc., that person can get in touch with Travel Line for the information, and they will be able to get the information conveniently.</p>
<a href="http://www.sme.com.bd"><p><strong>SME: Online Advisory Service. </strong> </p></a>
<p>BIID launched an integrated initiative in Bangladesh to facilitate the rapid growth of the Micro, Small and Medium Enterprises (MSMEs) with the help of ICT in addressing their problem and providing suitable solution to them. Developing the ICT-based platform to offer information and services for the rural enterprises will be an effective strategy to enhance the competitiveness of the rural MSMEs who have, among others, need for information on new markets, better business practices, and business promotion ideas where technology can become the catalyst to help the enterprises access the same. Empowering through new market linkages and building capacity of the MSMEs will ultimately contribute to the growth and competitiveness in this sector. MSME portal will also be focusing on the access to finance issue as well as training facilities for the MSMEs&#39;.</p>
<a href="http://www.eclinicbd.com"><p><strong>e-Clinic: Bringing Quality Health Service in Rural Areas</strong></p></a>
<p>e-Clinic: Bringing Quality Health Service in Rural AreasTelemedicine has been identified as one of the most potential tool to bring quality health service in rural areas. Considering the present health care facilities in Bangladesh, BIID has taken the initiative to start an interactive healthcare facility by utilizing modern technology and telecommunications. The e-Clinic project will cover the awareness building initiatives on health care among the rural communities and will use video consultations and other ICT based tools to offer basic primary health care services in rural settings. The rural underprivileged communities, mainly the women and children groups will be served with quality health care facilities of which they are deprived most. In the pilot phase, there will be a Central Management Unit located in Dhaka equipped with 
    &#39;state of art&#39; technologies and qualified health professionals, and 10 Service Delivery Points at different parts of the country with basic ICT infrastructure. The rural communities will be served in a sustainable manner by offering e-health facilities with the support of existing health service providers including the health professionals working in the rural areas. Continued Medical Education (CME) will also be introduced through the network of e-Clinic</p>
<a href="http://www.complain.com.bd"><p><strong>e-Complain: Providing a Platform to Promote Rights Based Activities </strong></p></a>
<p>BIID has introduced an ICT enabled web based consumer rights advocacy portal and online complaint handling mechanism, http://www.complain.com.bd. This unique web portal will allow the consumers a distinct platform and opportunity to be vocal about their rights, concerns and issues. Simultaneously the purpose is also to raise awareness, educate and empower the consumer on consumer rights and the legal protection afforded to them under the newly promulgated `Consumer Protection Act 2008'.</p>
<p><strong>District Resource Center: Developing Local Support Services for Telecenters </strong> </p>
<p>BIID is the designated District Resource Center(DRC) for Dhaka district.A DRC is a district coordinating body located in a district headquarter, which is to be designed as a hub for promoting activities surrounding building information and knowledge system for all citizens. DRCs are conceptualized as independent institutions to be affiliated with the BTN. DRC is the official institution to promote and support entrepreneurs and institutions in establishment and operation of telecenters and other type of public access to information and knowledge through ICTs. To ensure sustainability and quality of services, DRC&#39;s will charge nominal fees for its diversified services.</p>
<p><strong>Batighar: A business model for sustainable telecenters </strong> </p>
<p>After successful piloting phase, BIID has introduced the Batighar business model for scaling up in all over the country. Batighar, the name derived from the English word 
    &quot;lighthouse&quot;, is meant to show people correct direction. Recently, BIID and Pacific Telecom Ltd., only CDMA operator in Bangladesh has signed agreement to establish 500 Batighar centres all over the country by 2011 and 5000 centres by 2015. This particular business model can be distinctively characterized as a structured commercial model for for-profit telecenter ventures, which, are undertaken by entrepreneurs, businesses and organizations. It can also be termed as 
    &quot;entrepreneurship model&quot;.</p>