<p><strong>Supporting and Scaling up of GP CICs : </strong></p>
<p>BIID is engaged in supporting GP with their GP Community Information Center; to replicate and expand the existing number of CIC's across the country from 500 to over 1000. BIID is also engaged in the process to build the capacity of the CIC entrepreneurs to provide better services and facilities to the customers thereby adding value to the user experience of the customers. </p>
<p><strong>Agricultural Services for Rural Farmers : </strong></p>
<p>BIID's agricultural service for rural farmers, e-Krishok, is a campaign which is aimed at farmers with the desired goal of providing services from which farmers will benefit both in terms of their farming activities and opening up opportunities in new avenues which will ultimately translate into increased income for farmers. Farmers with any problem or query or issue which is related to agriculture can go to their local GP Community Information Center and receive the information that they are seeking. The information will be provided to them in a timely and quick manner, so that the farmers can get on with their activities. With such timely and appropriate information, farmers will be able to maximize their economic gain; enabling them to achieve income growth through agricultural activities. </p>
<p><strong>Online Market Linkage : </strong></p>
<p>The SME portal is basically a market linkage mechanism whereby small and medium producers and buyers can get in touch with each other for mutual benefit. The web portal can be accessed through http://www.sme.com.bd . Through this market linkage mechanism, SME's will be able to increase trade and reduce their costs. Other components of the SME portal is information sharing and market awareness building for the SME's. </p>
<p><strong>Providing a Platform to Promote Rights Based Activities : </strong></p>
<p>BIID has introduced an ICT enabled web based consumer rights advocacy portal and online complaint handling mechanism, http://www.complain.com.bd . This unique web portal will allow the consumers a distinct platform and opportunity to be vocal about their rights, concerns and issues. Simultaneously the purpose is also to raise awareness, educate and empower the consumer on consumer rights and the legal protection afforded to them under the newly promulgated `Consumer Protection Act 2008'. </p>
<p><strong>Consultancy : </strong></p>
<p>Although it came into being in 2008, the leadership behind BIID draws on many years of experience and exposures to ICT for Development (ICT4D) both home and abroad. BIID offers a range of consulting services that are aimed at contributing to improve livelihood, business development of enterprises and initiatives engaged in ICT enabled knowledge based services. </p>
<p><strong>Research and Development : </strong></p>
<p>Research and Development is at the core of BIIDs approach to ICT for development. R&amp;D services offered by BIID are aimed at development of business models, services and community outreach strategies for Telecentres and other ICT4D initiatives in rural Bangladesh. </p>
<p><strong>Content Creation and Delivery : </strong></p>
<p>Useful and user friendly content is vital in delivering communication services targeted to rural entrepreneurs and communities. Supported by its competence in R&amp;D, BIID specializes in facilitating development of general and location-specific content through its linkages with academic community, research organizations, private and public providers of information. </p>
<p><strong>Knowledge and Skills Development : </strong></p>
<p>Based on its understanding of specific training needs of human resources engaged in operation of ICT4D projects and in the provision of information based service delivery mechanism, BIID offers skill development support for prospective organizations and service providers. </p>
<p><strong>Knowledge Transfer : </strong></p>
<p>The leadership behind BIID has developed a knowledge base on ICT4D through active participation and sharing with local and international forums. BIID plans to continuously build on it by working in the field so that it can become a major contributor of knowledge to practitioners, researchers, policymakers and other stakeholders both home and abroad through capturing the lessons and sharing with relevant stakeholders. </p>
<p><strong>Monitoring and Evaluation : </strong></p>
<p>henever BIID is engaged in an intervention, BIID takes care to ensure to monitor activities taking place and to evaluate their impact with respect to the desired aims and goals.</p>
